from pathlib import Path
from html import escape as e
import json,re
R=Path(__file__).resolve().parents[1];D=json.loads((R/'content.json').read_text())
def img(src,alt='',cls='',prefix='',eager=False):return f'<img src="{prefix}{src}" alt="{e(alt)}" class="{cls}" loading="{"eager" if eager else "lazy"}" decoding="async">' if src else ''
def sectionhead(k,title,link='',label=''):
 return f'<div class="section-heading"><div><p class="eyebrow">{k}</p><h2>{title}</h2></div>'+ (f'<a class="text-link" href="{link}">{label} ↗</a>' if link else '')+'</div>'
def articlecard(a,i=0):
 return f'''<a class="article-card" href="articles/{a['id']}.html" data-search="{e(a['name'].lower())}"><div class="article-image">{img(a.get('image',''),a['name'])}<span class="round-button">↗</span></div><p class="eyebrow">ЗНАНИЯ / {max(1, round(sum(len(b['text'].split()) for b in a['blocks'])/180))} МИН ЧТЕНИЯ</p><h3>{e(a['name'])}</h3></a>'''
def contact():return '''<section class="contact-section wrap" id="form"><div><p class="eyebrow">КОНТАКТЫ</p><h2>Хорошее пиво<br>начинается<br><em>с разговора.</em></h2><p>Поможем выбрать набор, обсудим индивидуальный рецепт<br class="desktop-only"> и ответим на вопросы о домашнем пивоварении.</p><a class="contact-email" href="mailto:zernabor@mail.ru">zernabor@mail.ru ↗</a></div><div class="contact-card"><span class="small-label">ЕСТЬ ИДЕЯ ИЛИ ВОПРОС?</span><h3>Давайте сварим<br>что-нибудь своё.</h3><button class="button" data-order="Вопрос о пивоварении">Написать нам <span>↗</span></button><p class="muted">Или заходите в сообщество</p><div class="socials"><a href="https://t.me/bodreevbrew" target="_blank" rel="noopener">Telegram ↗</a><a href="https://www.youtube.com/@BodreevShow" target="_blank" rel="noopener">YouTube ↗</a><a href="https://boosty.to/bodreevbrew" target="_blank" rel="noopener">Boosty ↗</a><a href="https://www.youtube.com/@NaZolotomPrudu" target="_blank" rel="noopener">На Золотом Пруду ↗</a></div></div></section>'''
from v2_templates import chrome,product,homepage,recipespage
body=homepage(D)
(R/'index.html').write_text(chrome('Домашнее пивоварение',body,'home'))
def pagehero(k,title,desc):return f'<section class="page-hero wrap"><p class="eyebrow">{k}</p><h1>{title}</h1><p>{desc}</p></section>'
recipes='';templates=''
for i,p in enumerate(D['recipes']):
 recipes+=f'''<button class="recipe-card" data-recipe="recipe-{p['id']}" data-search="{e(p['name'].lower())}" data-new="{str(p['new']).lower()}"><div class="recipe-image">{img(p['image'],p['name'])}<span class="recipe-badge">{'НОВИНКА' if p['new'] else 'РЕЦЕПТ'}</span></div><div class="recipe-card-copy"><span class="card-index">{i+1:02} / BODREEVSHOW</span><h3>{e(p['name'])}</h3><span class="text-link">Открыть рецепт ↗</span></div></button>'''
 templates+=f'''<template id="recipe-{p['id']}"><p class="eyebrow">СБОРНИК РЕЦЕПТОВ</p><h2 id="reader-title">{e(p['name'])}</h2><div class="reader-actions"><button class="filter" data-save-recipe="recipe-{p['id']}" aria-pressed="false">♡ Сохранить</button><button class="filter" data-print-recipe>Распечатать</button><button class="filter" data-copy-recipe>Ссылка на рецепт ↗</button></div><div class="recipe-link" hidden><label>Ссылка на рецепт<input readonly aria-label="Ссылка на рецепт"></label></div><div class="recipe-reader"><div>{img(p['image'],p['name'])}</div><div class="prose">{''.join('<p>'+e(t)+'</p>' for t in p['blocks'])}<button class="button" data-download-recipe="{e(p['name'])}">Скачать рецепт ↓</button></div></div></template>'''
body=recipespage(D,templates)
(R/'recipes.html').write_text(chrome('Рецепты',body,'recipes'))
valid=[a for a in D['articles'] if not a.get('error')]
body=pagehero('МАСТЕРСКАЯ / БАЗА ЗНАНИЙ','Разобраться.<br><em>Попробовать. Понять.</em>','Полезные статьи, советы начинающим пивоварам и новости. Разбираемся в процессе — от выбора солода до хранения пива.')+f'''<section class="wrap section page-content"><div class="catalog-toolbar"><p>50 статей о домашнем пивоварении + 1 недоступный исходник</p><label class="search"><span>⌕</span><input type="search" data-search-target=".article-card" placeholder="Хмель, брожение, вода…" aria-label="Поиск статьи"></label></div><div class="article-grid digest-grid">{''.join(articlecard(a,i) for i,a in enumerate(valid))}</div><p class="empty-state" hidden>Материал не найден. Попробуйте другое слово.</p></section>'''
(R/'digest.html').write_text(chrome('Дайджест',body,'digest'))
(R/'articles').mkdir(exist_ok=True)
for a in valid:
 paragraphs='';toc=[]
 for j,b in enumerate(a['blocks']):
  if b['text']==a['name']:continue
  heading=b['type']=='heading' and len(b['text'])<100
  if heading:
   anchor='section-'+str(j);toc.append((anchor,b['text']));paragraphs+=f'<h2 id="{anchor}">{e(b["text"])}</h2>'
  else:paragraphs+='<p>'+e(b['text'])+'</p>'
 toc_html=''.join(f'<a href="#{anchor}">{e(title)}</a>' for anchor,title in toc)
 minutes=max(1,round(sum(len(b['text'].split()) for b in a['blocks'])/180))
 body=f'''<article class="wrap article-page"><a class="text-link" href="../digest.html">← Весь дайджест</a><p class="eyebrow">ДАЙДЖЕСТ / BODREEVSHOW</p><h1>{e(a['name'])}</h1>{img(a.get('image',''),a['name'],'article-cover','../',True)}<div class="article-layout"><aside><div class="article-aside"><p class="eyebrow">{minutes} МИН ЧТЕНИЯ</p><p>BodreevShow</p><nav class="article-toc" aria-label="Содержание статьи">{toc_html}</nav><p class="muted">Материал оригинального сайта. Сохранён 16 сентября 2026.</p><a class="text-link" href="{e(a['source'])}" target="_blank" rel="noopener">Первоисточник ↗</a><button class="text-link print-article" data-print-article>Распечатать</button></div></aside><div class="prose">{paragraphs}</div></div></article>'''
 (R/f'articles/{a["id"]}.html').write_text(chrome(a['name'],body,'digest','../'))
body=pagehero('ГИЛЬДИЯ ПИВОВАРОВ / МЕРЧ','Носи то,<br><em>чем увлечён.</em>','Футболки от Гильдии пивоваров. Для тех, кто любит хмель, солод и сам процесс.')+f'''<section class="wrap section page-content"><div class="merch-grid">{''.join(f'<article class="merch-card"><div class="merch-image">{img(p["image"],p["name"])}</div><p class="eyebrow">ФУТБОЛКА / ГИЛЬДИЯ ПИВОВАРОВ</p><h2>{e(p["name"])}</h2><div class="product-bottom"><strong>1 700 ₽</strong><button class="text-link" data-order="Футболка {e(p["name"])}">Заказать ↗</button></div></article>' for p in D['merch'])}</div><details class="size-chart"><summary>Таблица размеров <span>+</span></summary>{img(D['sizes'],'Таблица размеров футболок')}</details></section>{contact()}'''
(R/'merch.html').write_text(chrome('Мерч',body,'merch'))
body=pagehero('ИНСТРУМЕНТЫ / ПИВОТРОН','Пусть решит<br><em>случай.</em>','Пивная лотерея: загрузите список участников, проверьте билеты и выберите победителей.')+'''<section class="wrap section page-content raffle-layout"><div class="raffle-panel"><p class="eyebrow">01 / НАСТРОЙКИ</p><label class="file-drop">Файл участников<input id="raffle-file" type="file" accept=".xlsx,.xls,.csv"><span>Excel или CSV · до 5 МБ<br>Колонки: имя и сумма</span></label><div class="form-grid"><label>Цена билета, ₽<input id="ticket-price" type="number" min="1" value="100"></label><label>Победителей<input id="winner-count" type="number" min="1" max="100" value="1"></label></div><label>Исключить имя<input id="exclude-name" placeholder="Необязательно"></label><label class="checkbox"><input id="include-anonymous" type="checkbox"> Включить анонимных</label><button class="button" id="analyze">Анализировать файл ↗</button><p class="form-note">Обработка только в вашем браузере. Файл никуда не загружается. История сохраняется на этом устройстве.</p><p class="form-note">Оригинальный инструмент: © GaraElrik, <a href="mailto:Garas@xaker.ru">Garas@xaker.ru</a>. Здесь — отдельная локальная реализация.</p></div><div class="raffle-results"><p class="eyebrow">02 / УЧАСТНИКИ И РЕЗУЛЬТАТ</p><div id="raffle-status" role="status">Загрузите файл, чтобы увидеть участников и номера билетов.</div><div id="participants" class="table-scroll"></div><button class="button" id="draw" disabled>Выбрать победителей ↗</button><div id="winners" aria-live="polite"></div><details class="raffle-history"><summary>История на этом устройстве</summary><div id="history"></div></details></div></section>'''
(R/'random.html').write_text(chrome('Пивотрон',body,'random',extra='<script src="assets/xlsx.full.min.js" defer></script><script src="raffle-core.js" defer></script><script src="raffle.js" defer></script>'))
(R/'assets/favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="32" fill="#19241f"/><text x="14" y="45" fill="#f28b51" font-family="Georgia" font-size="44" font-weight="bold">B.</text></svg>')
(R/'robots.txt').write_text('User-agent: *\nDisallow: /\n');(R/'.nojekyll').touch()
print('Generated',len(valid)+5,'pages')
